import Navbar from '@/app/components/Navbar'
import '@/app/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <Navbar />
      <body>{children}</body>
    </html>
  )
}
